"""add_hardware_orders_and_stripe_fields

Revision ID: a463a2eb74cd
Revises: dc941537b4b1
Create Date: 2025-11-15 13:29:47.375622

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from cloud.api.database.models import GUID


# revision identifiers, used by Alembic.
revision: str = 'a463a2eb74cd'
down_revision: Union[str, None] = 'dc941537b4b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_orders',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('org_id', GUID(), nullable=True),
    sa.Column('plan_type', sa.String(length=20), nullable=False),
    sa.Column('total_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('prepaid_months', sa.Integer(), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('shipping_address', sa.JSON(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('activation_code', sa.String(length=50), nullable=False),
    sa.Column('code_activated_at', sa.DateTime(), nullable=True),
    sa.Column('activated_by_user_id', GUID(), nullable=True),
    sa.Column('subscription_starts_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_ends_at', sa.DateTime(), nullable=True),
    sa.Column('auto_renewal_starts_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('shipping_status', sa.String(length=50), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hardware_orders_activation_code', 'hardware_orders', ['activation_code'], unique=False)
    op.create_index('idx_hardware_orders_email', 'hardware_orders', ['customer_email', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_hardware_orders_shipping_status', 'hardware_orders', ['shipping_status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_hardware_orders_activation_code'), 'hardware_orders', ['activation_code'], unique=True)
    op.create_index(op.f('ix_hardware_orders_created_at'), 'hardware_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_hardware_orders_customer_email'), 'hardware_orders', ['customer_email'], unique=False)
    op.create_index(op.f('ix_hardware_orders_order_number'), 'hardware_orders', ['order_number'], unique=True)
    op.create_index(op.f('ix_hardware_orders_org_id'), 'hardware_orders', ['org_id'], unique=False)
    op.create_index(op.f('ix_hardware_orders_shipping_status'), 'hardware_orders', ['shipping_status'], unique=False)
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('organizations', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_organizations_stripe_customer_id'), 'organizations', ['stripe_customer_id'], unique=False)
    op.alter_column('share_links', 'allow_edit_prompt',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('share_links', 'allow_edit_prompt',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_organizations_stripe_customer_id'), table_name='organizations')
    op.drop_column('organizations', 'stripe_subscription_id')
    op.drop_column('organizations', 'stripe_customer_id')
    op.drop_index(op.f('ix_hardware_orders_shipping_status'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_org_id'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_order_number'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_customer_email'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_created_at'), table_name='hardware_orders')
    op.drop_index(op.f('ix_hardware_orders_activation_code'), table_name='hardware_orders')
    op.drop_index('idx_hardware_orders_shipping_status', table_name='hardware_orders')
    op.drop_index('idx_hardware_orders_email', table_name='hardware_orders')
    op.drop_index('idx_hardware_orders_activation_code', table_name='hardware_orders')
    op.drop_table('hardware_orders')
    # ### end Alembic commands ###
