"""add_link_name_and_allow_edit_prompt_to_share_links

Revision ID: dc941537b4b1
Revises: db7d78dfcf08
Create Date: 2025-11-14 22:39:30.050179

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc941537b4b1'
down_revision: Union[str, None] = 'db7d78dfcf08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activation_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('activation_codes', 'uses_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('activation_codes', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('activation_codes', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('activation_codes', 'one_per_user',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('idx_activation_codes_active'), table_name='activation_codes')
    op.create_index(op.f('ix_activation_codes_active'), 'activation_codes', ['active'], unique=False)
    op.alter_column('captures', 'evaluation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_captures_evaluation_status'), 'captures', ['evaluation_status'], unique=False)
    op.alter_column('code_redemptions', 'redeemed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_code_redemptions_user'), table_name='code_redemptions')
    op.drop_index(op.f('idx_code_redemptions_code'), table_name='code_redemptions')
    op.create_index('idx_code_redemptions_code', 'code_redemptions', ['code', sa.literal_column('redeemed_at DESC')], unique=False)
    op.drop_index(op.f('idx_code_redemptions_org'), table_name='code_redemptions')
    op.create_index('idx_code_redemptions_org', 'code_redemptions', ['org_id', sa.literal_column('redeemed_at DESC')], unique=False)
    op.create_index(op.f('ix_code_redemptions_code'), 'code_redemptions', ['code'], unique=False)
    op.create_index(op.f('ix_code_redemptions_org_id'), 'code_redemptions', ['org_id'], unique=False)
    op.create_index(op.f('ix_code_redemptions_user_id'), 'code_redemptions', ['user_id'], unique=False)
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=True)
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('organizations', 'allowed_devices',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('organizations', 'active_devices_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('organizations', 'code_granted_devices',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.alter_column('scheduled_triggers', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scheduled_triggers', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('scheduled_triggers', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('idx_triggers_device'), table_name='scheduled_triggers')
    op.drop_index(op.f('idx_triggers_status'), table_name='scheduled_triggers')
    op.drop_index(op.f('idx_triggers_type'), table_name='scheduled_triggers')
    op.create_index(op.f('ix_scheduled_triggers_device_id'), 'scheduled_triggers', ['device_id'], unique=False)
    op.create_index(op.f('ix_scheduled_triggers_scheduled_at'), 'scheduled_triggers', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_scheduled_triggers_status'), 'scheduled_triggers', ['status'], unique=False)
    op.create_index(op.f('ix_scheduled_triggers_trigger_type'), 'scheduled_triggers', ['trigger_type'], unique=False)
    op.add_column('share_links', sa.Column('link_name', sa.String(length=255), nullable=True))
    op.add_column('share_links', sa.Column('allow_edit_prompt', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('share_links', 'allow_edit_prompt')
    op.drop_column('share_links', 'link_name')
    op.drop_index(op.f('ix_scheduled_triggers_trigger_type'), table_name='scheduled_triggers')
    op.drop_index(op.f('ix_scheduled_triggers_status'), table_name='scheduled_triggers')
    op.drop_index(op.f('ix_scheduled_triggers_scheduled_at'), table_name='scheduled_triggers')
    op.drop_index(op.f('ix_scheduled_triggers_device_id'), table_name='scheduled_triggers')
    op.create_index(op.f('idx_triggers_type'), 'scheduled_triggers', ['trigger_type'], unique=False)
    op.create_index(op.f('idx_triggers_status'), 'scheduled_triggers', ['status', 'sent_at'], unique=False)
    op.create_index(op.f('idx_triggers_device'), 'scheduled_triggers', ['device_id', 'scheduled_at'], unique=False)
    op.alter_column('scheduled_triggers', 'retry_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('scheduled_triggers', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('scheduled_triggers', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('organizations', 'code_granted_devices',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('organizations', 'active_devices_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('organizations', 'allowed_devices',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('organizations', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'free'::character varying"),
               nullable=False)
    op.alter_column('devices', 'status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'manufactured'::character varying"),
               existing_nullable=True)
    op.drop_index(op.f('ix_code_redemptions_user_id'), table_name='code_redemptions')
    op.drop_index(op.f('ix_code_redemptions_org_id'), table_name='code_redemptions')
    op.drop_index(op.f('ix_code_redemptions_code'), table_name='code_redemptions')
    op.drop_index('idx_code_redemptions_org', table_name='code_redemptions')
    op.create_index(op.f('idx_code_redemptions_org'), 'code_redemptions', ['org_id'], unique=False)
    op.drop_index('idx_code_redemptions_code', table_name='code_redemptions')
    op.create_index(op.f('idx_code_redemptions_code'), 'code_redemptions', ['code'], unique=False)
    op.create_index(op.f('idx_code_redemptions_user'), 'code_redemptions', ['user_id'], unique=False)
    op.alter_column('code_redemptions', 'redeemed_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_index(op.f('ix_captures_evaluation_status'), table_name='captures')
    op.alter_column('captures', 'evaluation_status',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_activation_codes_active'), table_name='activation_codes')
    op.create_index(op.f('idx_activation_codes_active'), 'activation_codes', ['active'], unique=False)
    op.alter_column('activation_codes', 'one_per_user',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('activation_codes', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('activation_codes', 'valid_from',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False)
    op.alter_column('activation_codes', 'uses_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('activation_codes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###
