"""Initial schema

Revision ID: 8af79cab0d8d
Revises: 
Create Date: 2025-11-06 22:47:32.104237

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af79cab0d8d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('friendly_name', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_ip', sa.String(length=45), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('device_version', sa.String(length=50), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_index('idx_devices_org_last_seen', 'devices', ['org_id', sa.literal_column('last_seen_at DESC')], unique=False)
    op.create_index(op.f('ix_devices_api_key'), 'devices', ['api_key'], unique=True)
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_org_id'), 'devices', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('supabase_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_index(op.f('ix_users_supabase_user_id'), 'users', ['supabase_user_id'], unique=True)
    op.create_table('captures',
    sa.Column('record_id', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('s3_image_key', sa.String(length=500), nullable=True),
    sa.Column('s3_thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('image_stored', sa.Boolean(), nullable=True),
    sa.Column('thumbnail_stored', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('agent_details', sa.JSON(), nullable=True),
    sa.Column('trigger_label', sa.String(length=100), nullable=True),
    sa.Column('normal_description_file', sa.String(length=500), nullable=True),
    sa.Column('capture_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_index('idx_captures_device_date', 'captures', ['device_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index('idx_captures_org_state_date', 'captures', ['org_id', 'state', sa.literal_column('captured_at DESC')], unique=False)
    op.create_index(op.f('ix_captures_captured_at'), 'captures', ['captured_at'], unique=False)
    op.create_index(op.f('ix_captures_device_id'), 'captures', ['device_id'], unique=False)
    op.create_index(op.f('ix_captures_ingested_at'), 'captures', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_captures_org_id'), 'captures', ['org_id'], unique=False)
    op.create_index(op.f('ix_captures_state'), 'captures', ['state'], unique=False)
    op.create_table('share_links',
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('share_type', sa.String(length=50), nullable=True),
    sa.Column('capture_id', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index('idx_share_links_expires', 'share_links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_share_links_created_at'), 'share_links', ['created_at'], unique=False)
    op.create_index(op.f('ix_share_links_device_id'), 'share_links', ['device_id'], unique=False)
    op.create_index(op.f('ix_share_links_expires_at'), 'share_links', ['expires_at'], unique=False)
    op.create_index(op.f('ix_share_links_org_id'), 'share_links', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_share_links_org_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_expires_at'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_device_id'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_created_at'), table_name='share_links')
    op.drop_index('idx_share_links_expires', table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_captures_state'), table_name='captures')
    op.drop_index(op.f('ix_captures_org_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_ingested_at'), table_name='captures')
    op.drop_index(op.f('ix_captures_device_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_captured_at'), table_name='captures')
    op.drop_index('idx_captures_org_state_date', table_name='captures')
    op.drop_index('idx_captures_device_date', table_name='captures')
    op.drop_table('captures')
    op.drop_index(op.f('ix_users_supabase_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_org_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_api_key'), table_name='devices')
    op.drop_index('idx_devices_org_last_seen', table_name='devices')
    op.drop_table('devices')
    op.drop_table('organizations')
    # ### end Alembic commands ###
